# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20180118_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
